all: 
	sh/build.sh

test: all
	build/libsemigroups/test_bmat8_enum "[quick]"

3: 
	@sh/run.sh 3

4: 
	@sh/run.sh 4

5: 
	@sh/run.sh 5

6: 
	@sh/run.sh 6

7: 
	@sh/run.sh 7

8: 
	@sh/run.sh 8

clean:  
	rm -rf build
